version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: serviceflow-postgres
    restart: always
    environment:
      POSTGRES_DB: serviceflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: serviceflow-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: serviceflow-zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: serviceflow-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: serviceflow-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: serviceflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  realtime:
    build:
      context: ./realtime
      dockerfile: Dockerfile
    container_name: serviceflow-realtime
    restart: unless-stopped
    ports:
      - "3001:3001"

volumes:

  postgres-data:

  mongodb-data: